THEMES = {'dark_amber': {'colors': {'primaryColor': '#ffd740',
                           'primaryLightColor': '#ffff74',
                           'primaryTextColor': '#ffffff',
                           'secondaryColor': '#232629',
                           'secondaryDarkColor': '#31363b',
                           'secondaryLightColor': '#4f5b62',
                           'secondaryTextColor': '#ffffff'},
                'qt_material_theme': 'dark_amber.xml'},
 'dark_blue': {'colors': {'primaryColor': '#448aff',
                          'primaryLightColor': '#83b9ff',
                          'primaryTextColor': '#ffffff',
                          'secondaryColor': '#232629',
                          'secondaryDarkColor': '#31363b',
                          'secondaryLightColor': '#4f5b62',
                          'secondaryTextColor': '#ffffff'},
               'qt_material_theme': 'dark_blue.xml'},
 'dark_cyan': {'colors': {'primaryColor': '#4dd0e1',
                          'primaryLightColor': '#88ffff',
                          'primaryTextColor': '#ffffff',
                          'secondaryColor': '#232629',
                          'secondaryDarkColor': '#31363b',
                          'secondaryLightColor': '#4f5b62',
                          'secondaryTextColor': '#ffffff'},
               'qt_material_theme': 'dark_cyan.xml'},
 'dark_lightgreen': {'colors': {'primaryColor': '#8bc34a',
                                'primaryLightColor': '#bef67a',
                                'primaryTextColor': '#ffffff',
                                'secondaryColor': '#232629',
                                'secondaryDarkColor': '#31363b',
                                'secondaryLightColor': '#4f5b62',
                                'secondaryTextColor': '#ffffff'},
                     'qt_material_theme': 'dark_lightgreen.xml'},
 'dark_pink': {'colors': {'primaryColor': '#ff4081',
                          'primaryLightColor': '#ff79b0',
                          'primaryTextColor': '#ffffff',
                          'secondaryColor': '#232629',
                          'secondaryDarkColor': '#31363b',
                          'secondaryLightColor': '#4f5b62',
                          'secondaryTextColor': '#ffffff'},
               'qt_material_theme': 'dark_pink.xml'},
 'dark_purple': {'colors': {'primaryColor': '#ab47bc',
                            'primaryLightColor': '#df78ef',
                            'primaryTextColor': '#ffffff',
                            'secondaryColor': '#232629',
                            'secondaryDarkColor': '#31363b',
                            'secondaryLightColor': '#4f5b62',
                            'secondaryTextColor': '#ffffff'},
                 'qt_material_theme': 'dark_purple.xml'},
 'dark_red': {'colors': {'primaryColor': '#ff1744',
                         'primaryLightColor': '#ff616f',
                         'primaryTextColor': '#ffffff',
                         'secondaryColor': '#232629',
                         'secondaryDarkColor': '#31363b',
                         'secondaryLightColor': '#4f5b62',
                         'secondaryTextColor': '#ffffff'},
              'qt_material_theme': 'dark_red.xml'},
 'dark_teal': {'colors': {'primaryColor': '#1de9b6',
                          'primaryLightColor': '#6effe8',
                          'primaryTextColor': '#ffffff',
                          'secondaryColor': '#232629',
                          'secondaryDarkColor': '#31363b',
                          'secondaryLightColor': '#4f5b62',
                          'secondaryTextColor': '#ffffff'},
               'qt_material_theme': 'dark_teal.xml'},
 'dark_yellow': {'colors': {'primaryColor': '#ffff00',
                            'primaryLightColor': '#ffff5a',
                            'primaryTextColor': '#ffffff',
                            'secondaryColor': '#232629',
                            'secondaryDarkColor': '#31363b',
                            'secondaryLightColor': '#4f5b62',
                            'secondaryTextColor': '#ffffff'},
                 'qt_material_theme': 'dark_yellow.xml'},
 'light_amber': {'colors': {'primaryColor': '#ffc400',
                            'primaryLightColor': '#fff64f',
                            'primaryTextColor': '#3c3c3c',
                            'secondaryColor': '#f5f5f5',
                            'secondaryDarkColor': '#e6e6e6',
                            'secondaryLightColor': '#ffffff',
                            'secondaryTextColor': '#555555'},
                 'qt_material_theme': 'light_amber.xml'},
 'light_blue': {'colors': {'primaryColor': '#2979ff',
                           'primaryLightColor': '#75a7ff',
                           'primaryTextColor': '#3c3c3c',
                           'secondaryColor': '#f5f5f5',
                           'secondaryDarkColor': '#e6e6e6',
                           'secondaryLightColor': '#ffffff',
                           'secondaryTextColor': '#555555'},
                'qt_material_theme': 'light_blue.xml'},
 'light_blue_500': {'colors': {'primaryColor': '#03a9f4',
                               'primaryLightColor': '#67daff',
                               'primaryTextColor': '#3c3c3c',
                               'secondaryColor': '#f5f5f5',
                               'secondaryDarkColor': '#e6e6e6',
                               'secondaryLightColor': '#ffffff',
                               'secondaryTextColor': '#555555'},
                    'qt_material_theme': 'light_blue_500.xml'},
 'light_cyan': {'colors': {'primaryColor': '#00e5ff',
                           'primaryLightColor': '#6effff',
                           'primaryTextColor': '#3c3c3c',
                           'secondaryColor': '#f5f5f5',
                           'secondaryDarkColor': '#e6e6e6',
                           'secondaryLightColor': '#ffffff',
                           'secondaryTextColor': '#555555'},
                'qt_material_theme': 'light_cyan.xml'},
 'light_cyan_500': {'colors': {'primaryColor': '#00bcd4',
                               'primaryLightColor': '#62efff',
                               'primaryTextColor': '#3c3c3c',
                               'secondaryColor': '#f5f5f5',
                               'secondaryDarkColor': '#e6e6e6',
                               'secondaryLightColor': '#ffffff',
                               'secondaryTextColor': '#555555'},
                    'qt_material_theme': 'light_cyan_500.xml'},
 'light_lightgreen': {'colors': {'primaryColor': '#64dd17',
                                 'primaryLightColor': '#9cff57',
                                 'primaryTextColor': '#3c3c3c',
                                 'secondaryColor': '#f5f5f5',
                                 'secondaryDarkColor': '#e6e6e6',
                                 'secondaryLightColor': '#ffffff',
                                 'secondaryTextColor': '#555555'},
                      'qt_material_theme': 'light_lightgreen.xml'},
 'light_lightgreen_500': {'colors': {'primaryColor': '#8bc34a',
                                     'primaryLightColor': '#bef67a',
                                     'primaryTextColor': '#3c3c3c',
                                     'secondaryColor': '#f5f5f5',
                                     'secondaryDarkColor': '#e6e6e6',
                                     'secondaryLightColor': '#ffffff',
                                     'secondaryTextColor': '#555555'},
                          'qt_material_theme': 'light_lightgreen_500.xml'},
 'light_orange': {'colors': {'primaryColor': '#ff3d00',
                             'primaryLightColor': '#ff7539',
                             'primaryTextColor': '#3c3c3c',
                             'secondaryColor': '#f5f5f5',
                             'secondaryDarkColor': '#e6e6e6',
                             'secondaryLightColor': '#ffffff',
                             'secondaryTextColor': '#555555'},
                  'qt_material_theme': 'light_orange.xml'},
 'light_pink': {'colors': {'primaryColor': '#ff4081',
                           'primaryLightColor': '#ff79b0',
                           'primaryTextColor': '#3c3c3c',
                           'secondaryColor': '#f5f5f5',
                           'secondaryDarkColor': '#e6e6e6',
                           'secondaryLightColor': '#ffffff',
                           'secondaryTextColor': '#555555'},
                'qt_material_theme': 'light_pink.xml'},
 'light_pink_500': {'colors': {'primaryColor': '#e91e63',
                               'primaryLightColor': '#ff6090',
                               'primaryTextColor': '#3c3c3c',
                               'secondaryColor': '#f5f5f5',
                               'secondaryDarkColor': '#e6e6e6',
                               'secondaryLightColor': '#ffffff',
                               'secondaryTextColor': '#555555'},
                    'qt_material_theme': 'light_pink_500.xml'},
 'light_purple': {'colors': {'primaryColor': '#e040fb',
                             'primaryLightColor': '#ff79ff',
                             'primaryTextColor': '#3c3c3c',
                             'secondaryColor': '#f5f5f5',
                             'secondaryDarkColor': '#e6e6e6',
                             'secondaryLightColor': '#ffffff',
                             'secondaryTextColor': '#555555'},
                  'qt_material_theme': 'light_purple.xml'},
 'light_purple_500': {'colors': {'primaryColor': '#9c27b0',
                                 'primaryLightColor': '#d05ce3',
                                 'primaryTextColor': '#3c3c3c',
                                 'secondaryColor': '#f5f5f5',
                                 'secondaryDarkColor': '#e6e6e6',
                                 'secondaryLightColor': '#ffffff',
                                 'secondaryTextColor': '#555555'},
                      'qt_material_theme': 'light_purple_500.xml'},
 'light_red': {'colors': {'primaryColor': '#ff1744',
                          'primaryLightColor': '#ff616f',
                          'primaryTextColor': '#3c3c3c',
                          'secondaryColor': '#f5f5f5',
                          'secondaryDarkColor': '#e6e6e6',
                          'secondaryLightColor': '#ffffff',
                          'secondaryTextColor': '#555555'},
               'qt_material_theme': 'light_red.xml'},
 'light_red_500': {'colors': {'primaryColor': '#f44336',
                              'primaryLightColor': '#ff7961',
                              'primaryTextColor': '#3c3c3c',
                              'secondaryColor': '#f5f5f5',
                              'secondaryDarkColor': '#e6e6e6',
                              'secondaryLightColor': '#ffffff',
                              'secondaryTextColor': '#555555'},
                   'qt_material_theme': 'light_red_500.xml'},
 'light_teal': {'colors': {'primaryColor': '#1de9b6',
                           'primaryLightColor': '#6effe8',
                           'primaryTextColor': '#3c3c3c',
                           'secondaryColor': '#f5f5f5',
                           'secondaryDarkColor': '#e6e6e6',
                           'secondaryLightColor': '#ffffff',
                           'secondaryTextColor': '#555555'},
                'qt_material_theme': 'light_teal.xml'},
 'light_teal_500': {'colors': {'primaryColor': '#009688',
                               'primaryLightColor': '#52c7b8',
                               'primaryTextColor': '#3c3c3c',
                               'secondaryColor': '#f5f5f5',
                               'secondaryDarkColor': '#e6e6e6',
                               'secondaryLightColor': '#ffffff',
                               'secondaryTextColor': '#555555'},
                    'qt_material_theme': 'light_teal_500.xml'},
 'light_yellow': {'colors': {'primaryColor': '#ffea00',
                             'primaryLightColor': '#ffff56',
                             'primaryTextColor': '#3c3c3c',
                             'secondaryColor': '#f5f5f5',
                             'secondaryDarkColor': '#e6e6e6',
                             'secondaryLightColor': '#ffffff',
                             'secondaryTextColor': '#555555'},
                  'qt_material_theme': 'light_yellow.xml'}}
